service: aws-node-swapi
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:783895869090:table/PeopleTable

functions:
  uploadPeople:
    handler: src/uploadPeople.uploadPeople
    events:
      - httpApi:
          path: /subirdatos
          method: get
  createPeople:
    handler: src/addPeople.addPeople
    events:
      - httpApi:
          path: /personas
          method: post
  getPeoples:
    handler: src/getPeoples.getPeoples
    events:
      - httpApi:
          path: /personas
          method: get
  getPeople:
    handler: src/getPeople.getPeople
    events:
      - httpApi:
          path: /personas/{id}
          method: get
  updatePeople:
    handler: src/updatePeople.updatePeople
    events:
      - httpApi:
          path: /personas/{id}
          method: put
  deletePeople:
    handler: src/deletePeople.deletePeople
    events:
      - httpApi:
          path: /personas/{id}
          method: delete

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
